#!/bin/bash -e

function showHelp() {
cat << EOF
Usage:
  build [options] <tasks(s)> <python version(s)>

Options:
  -b, --build-only  only build dependency images
  -d, --devenv      only build the developer environment image
  -h, --help        display this help information
  -v, --verbose     print output to console during container execution
      --gpu         enable gpu support on task execution
      --push        push all built images to repository

Default:
  run unit tests and type check for 3.8-3.11 as well as lint and docs

Python Versions:
  3.8-3.11 are supported

Tasks:
  unit    run unit tests
  type    run typecheck
  lint    run static code analysis
  docs    generate documentation
  qdocs   generate documentation using cached notebooks

Note:
  lint and docs are always performed on python 3.11
EOF
exit $1
}

options=$(getopt -l "help,verbose,gpu,build-only,devenv,push" -o "hvbd" -n "build" -- "$@")
eval set -- "$options"
while true; do
    case "$1" in
        -h|--help)       showHelp;;
        -v|--verbose)    export verbose=1;;
        --gpu)           export gpuflag="--gpus all";;
        -b|--build-only) build_only=1;;
        -d|--devenv)     devenv=1;;
        --push)          export push_to_repo=1;;
        --)              shift; break;;
    esac
    shift
done

if [[ -f .settings ]]; then
    if [[ $(cat .settings | grep save-build-images) ]]; then
        export save_build_images="true"
    fi
fi

# declare lookup maps
declare -A supported_pvers=([3.8]=1 [3.9]=1 [3.10]=1 [3.11]=1)
declare -A supported_tasks=([unit]=1 [type]=1)
declare -A supported_other=([lint]=1 [docs]=1 [qdocs]=1)

# generate python and task lists
declare -A pvers; declare -A tasks;
count=0; c_pvers=0; c_tasks=0; c_other=0;

# validate args
for arg do
    if [[ $arg == -* ]]; then continue; fi
    if [[ ${supported_pvers["$arg"]} ]]; then pvers[$arg]=1; ((++c_pvers)); fi
    if [[ ${supported_tasks["$arg"]} ]]; then tasks[$arg]=1; ((++c_tasks)); fi
    if [[ ${supported_other["$arg"]} ]]; then tasks[$arg]=1; ((++c_other)); fi
    ((++count))
done

# show help if arg count mismatch
if [[ $((c_pvers + c_tasks + c_other)) != $count ]]; then showHelp 1; fi

# set defaults if not specified
if [[ ! $build_only ]]; then
    if [[ $count == 0 || ($c_pvers == 0 && $c_tasks != 0) ]]; then pvers=([3.8]=1 [3.9]=1 [3.10]=1 [3.11]=1); fi
    if [[ $count == 0 || ($c_tasks == 0 && $c_pvers != 0) ]]; then tasks[unit]=1; tasks[type]=1; fi
    if [[ $count == 0 ]]; then tasks[lint]=1; fi
fi

# generate "task-pver" jobs
declare -A jobs;
for task in "${!tasks[@]}"; do
    case "$task" in
        lint|docs|qdocs) jobs["$task-3.11"]=1;;
        *) for pver in "${!pvers[@]}"; do jobs["$task-$pver"]=1; done;;
    esac
done
if [[ ${tasks[lint]} || ${tasks[docs]} || ${tasks[qdocs]} ]]; then pvers[3.11]=1; fi

export builder_name="daml"
if [[ -z $(docker builder ls --format '{{.Name}}' | grep $builder_name) ]]; then
    echo "builder instance named $builder_name doesn't exist, creating it now..."
    docker builder create \
        --driver docker-container \
        --bootstrap \
        --name $builder_name
fi

function post_build_cleanup() {
    temp=$1
    tag=$2
    container_name=$3

    rm -f $temp

    if [[ $(docker container ls --all --filter name=$container_name) ]]; then
        docker container rm --force $container_name &> /dev/null
    fi

    if [[ -z $save_build_images && $(docker image ls --filter reference=$tag) ]]; then
        docker image rm --force $tag &> /dev/null
    fi
}

function build_image() {
    tag=$1
    target=$2
    python_version=$3
    cache_from_tag=$4

    base_tag="${base_image}:${python_version}"
    deps_tag="${deps_image}-${python_version}"
    build_tag="${build_image}-${python_version}"

    if [[ $(docker manifest inspect $base_tag) ]]; then
        image_args="--build-arg base_image=$base_tag"
    fi

    if [[ $(docker manifest inspect $deps_tag) ]]; then
        image_args="$image_args --build-arg deps_image=$deps_tag"
    fi

    if [[ $(docker manifest inspect $build_tag) ]]; then
        image_args="$image_args --build-arg build_image=$build_tag"
    fi

    python_optimization_args="\
        --build-arg pyenv_enable_opt=--enable-optimizations \
        --build-arg pyenv_with_lto=--with-lto"

    main_build_cache="${registry}/main/${target}-buildcache:${python_version}"

    cache_image="${tag/:/-buildcache:}"

    cache_from_arg="\
        --cache-from type=registry,ref=$main_build_cache \
        --cache-from type=registry,ref=$cache_image \
        --cache-from type=registry,ref=$cache_from_tag"

    # Writing to the cache means that you must be able to push to the registry, therefore
    # don't want to force users to login to the registry just to build.
    if [[ $push_to_repo ]]; then
        cache_to_arg="--cache-to type=registry,mode=max,image-manifest=true,ref=$cache_image"
        # Only update the main build cache via pipeline builds running the main branch
        if [[ $CI_COMMIT_BRANCH && $CI_DEFAULT_BRANCH && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH ]]; then
            cache_to_arg="${cache_to_arg} --cache-to type=registry,mode=max,image-manifest=true,ref=$main_build_cache"
        fi
    fi

    output_arg="--output type=image,name=$tag"
    if [[ $push_to_repo ]]; then
        output_arg="${output_arg},push=true"
    fi

    if [[ $save_build_images || $load_image ]]; then
        # By default the docker-container driver doesn't load images to the
        # local docker images store, these args will cause it to do so.
        load_arg="--tag ${tag} --load"
    fi

    docker_build_cmd="docker buildx build $verbosity \
        $load_arg \
        --builder $builder_name \
        --build-arg python_version=$python_version \
        $python_optimization_args \
        $image_args \
        $cache_from_arg \
        $cache_to_arg \
        $output_arg \
        --target $target \
        ."

    if [[ $verbose ]]; then
        echo "Building $tag..."
        echo $docker_build_cmd
        $docker_build_cmd
    else
        $docker_build_cmd &> /dev/null
    fi
}

function docker_run() {
    temp=$(mktemp)
    IFS=- read -r task pver <<< $1
    tag="${run_image}-${pver}"

    container_name="run-${task}-${pver}"
    if [[ $CI_PIPELINE_ID ]]; then
        container_name="${container_name}-${CI_PIPELINE_ID}"
    fi

    trap "post_build_cleanup $temp $tag $container_name" EXIT

    docker_run_args="--name $container_name $gpuflag $tag"

    if [[ $verbose ]]; then
        (echo "Running $container_name..."; echo docker run $docker_run_args $task; docker run $docker_run_args $task | tee -a $temp; exit ${PIPESTATUS[0]}) || result="FAILED"
    else
        docker run $docker_run_args $task &> $temp || result="FAILED"
    fi

    if [[ $result == "FAILED" ]]; then
        log_file="output/logs/daml-${task}-${pver}_failure_$(date +%s).log"
        echo "FAILED (see log file ${log_file})"
        mkdir -p output/logs
        cat $temp > $log_file
        if [[ ! $verbose ]]; then cat $temp; fi
        exitcode=1
    else
        if [[ ! $verbose ]]; then echo SUCCEEDED; fi
        case "$task" in
            unit|docs) docker cp $container_name:/daml/output ./;;
        esac
    fi

    exit $exitcode
}

function ensure_image() {
    target=$1
    python_version=$2

    if [[ $target == "pybase" ]]; then
        tag="${base_image}:${python_version}"
    elif [[ $target == "pydeps" ]]; then
        tag="${deps_image}-${python_version}"
    elif [[ $target == "build" ]]; then
        tag="${build_image}-${python_version}"
    else
        echo "unknown target: ${target}"
        exit 1
    fi

    # Rebuild and push the image on main branch commits, or just skip if exists
    if [[ $CI && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $(docker manifest inspect $tag > /dev/null 2>&1; echo $?) == 1 ]]; then
        build_image $tag $target $python_version $tag
    else
        echo "Verified $tag image in registry"
    fi

    # Base tag images do not have a main tag equivalent so we can skip main tag update
    if [[ $CI && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $push_to_repo && $target != pybase ]]; then
        # Replace the hash with "main" to form the main tag.
        main_tag="${tag/${deps_hash}/main}"
        local main_manifest=$(docker manifest inspect $main_tag 2> /dev/null) || true
        local hash_manifest=$(docker manifest inspect $tag 2> /dev/null) || true
        if [[ "$main_manifest" != "$hash_manifest" ]]; then
            echo "Updating $main_tag image with $deps_hash build..."
            docker pull $tag
            docker image tag $tag $main_tag
            docker push $main_tag
        else
            echo "$main_tag is up to date with $tag."
        fi
    fi
}

export -f post_build_cleanup
export -f build_image
export -f docker_run

export deps_hash=$(sha256sum poetry.lock | cut -c 1-8)

export registry="harbor.jatic.net/daml"
export base_image="${registry}/pybase"
export deps_image="${registry}/pydeps:${deps_hash}"
export build_image="${registry}/build:${deps_hash}"
export run_image="${registry}/run:${deps_hash}"

if [[ -z $verbose ]]; then
    verbosity="--quiet"
else
    keep_order="--keep-order"
fi
export verbosity

if [[ ${#pvers[@]} == 0 ]]; then pvers=([3.8]=1 [3.9]=1 [3.10]=1 [3.11]=1); fi

if [[ $build_only ]] || [[ $devenv ]]; then
    for pver in ${!pvers[@]}; do
        ensure_image pybase $pver
        ensure_image pydeps $pver
        if [[ $CI ]]; then
            ensure_image build $pver
        fi
    done

    if [[ $devenv ]]; then
        echo "Building devcontainer with python ${!pvers[@]}..."
        (cat Dockerfile && echo ENV versions=\"${!pvers[@]}\" && echo -n ${!pvers[@]} | xargs -d' ' -I{} echo COPY --chown=\${UID}/ --link --from=$deps_image-{} \${PYENV_ROOT}/ \${PYENV_ROOT}/) |
        docker build $verbosity --tag daml-devcontainer --target devcontainer -
        docker image prune -f
    fi

    exit $?
fi

for pver in ${!pvers[@]}; do
    export load_image=1
    build_image "${run_image}-${pver}" run $pver "${build_image}-${pver}"
done

# execute jobs
echo "Running ${!jobs[@]}..."
case ${#jobs[@]} in
    0)  showHelp 1;;
    1)  export verbose=1; docker_run ${!jobs[@]};;
    *)  LANG=C parallel $keep_order --lb --tag docker_run ::: ${!jobs[@]};;
esac
