#!/bin/bash

echo -e "\033[1;31mPlease ensure this script runs to completion!\033[0m"
echo

# Check for uv
if ! $(which uv 1> /dev/null); then echo "Install uv to continue: https://docs.astral.sh/uv/"; exit 1; fi

allowed=(3.9 3.10 3.11 3.12)
default=(3.11)

# Use arguments or prompt for python versions
if [[ $@ ]]; then
    input=$@
else
    read -p "Enter space delimited desired versions of python [supported: ${allowed[*]}] [default: ${default[*]}]: " input
fi

# Parse python version inputs
versions=()
if [[ $input ]]; then
    for token in ${input}; do
        token=$(echo $token | cut -d '.' -f 1,2)
        if [[ ! " ${allowed[*]} " =~ [[:space:]]${token}[[:space:]] ]]; then
            echo "Unrecognized input $token - skipping..."
            continue
        else
            versions+=($token)
        fi
    done
fi
if [ ${#versions[@]} == 0 ]; then
    echo "Unrecognized inputs, defaulting to ${default[*]}"
    versions=(${default[@]})
fi

# Install dataeval environment for each version of python
echo -n ${versions[*]} | xargs -n1 bash -c '\
    export UV_PROJECT_ENVIRONMENT=.venv-$0 && \
    echo "Creating python virtual environment for $0..." && \
    rm -rf $UV_PROJECT_ENVIRONMENT && \
    uv sync -p $0 --extra all'
echo -n ${versions[*]} | xargs -n1 bash -c '\
    echo "Finished installing dataeval for python $0 to .venv-$0"'
echo

echo
if [[ -v $REMOTE_CONTAINERS ]]; then
    echo -e '\033[1;37mActivate your desired virtual environment (e.g. \033[1;32msource .venv-'${versions[-1]}'/bin/activate\033[1;37m) before proceeding.'
else
    echo -e '\033[1;37mIt is now safe to reload the window (\033[1;32mDeveloper: Reload Window\033[1;37m) and select a Python interpreter (\033[1;32mPython: Select Interpreter\033[1;37m) from the Command Palette.'
fi
echo
