# This workflows will upload a Python Package using PyPI's Trusted Publisher feature: https://docs.pypi.org/trusted-publishers/adding-a-publisher/
name: Upload Python Package

on:
  push:
    tags: ['v*']

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment: 
      name: pypi-publish
      url: https://pypi.org/p/dataeval
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: uv build
      - run: uv publish --trusted-publishing always