###############################################################################
# Stage -- A child pipeline to run the DevSecOps components
###############################################################################
stages:
  - sr-compliance
  - unit-test
  - tr-compliance
  - dsor-compliance
  - advana-compliance
  - validate
  - summary

include:
  - component: gitlab.jatic.net/jatic/devsecops/components/sr-compliance@1.0.0
    inputs:
      package_name: "${PACKAGE_NAME}"
      tools_used: [pyproject, poetry, ruff]
      full_execution_on_commit: true
      allow_failure: true

  - component: gitlab.jatic.net/jatic/devsecops/components/unit-test@1.0.0
    inputs:
      stage: unit-test
      full_execution_on_commit: true
      package_name: "${PACKAGE_NAME}"
      marker: required
      dependency: required
      poetry_install_options: --only dev
      allow_failure: true

  - component: gitlab.jatic.net/jatic/devsecops/components/unit-test@1.0.0
    inputs:
      stage: unit-test
      full_execution_on_commit: true
      package_name: "${PACKAGE_NAME}"
      marker: optional
      dependency: optional
      poetry_install_options: --extras=onnx
      allow_failure: true

  - component: gitlab.jatic.net/jatic/devsecops/components/unit-test@1.0.0
    inputs:
      stage: unit-test
      full_execution_on_commit: true
      package_name: "${PACKAGE_NAME}"
      marker: optional
      dependency: required
      poetry_install_options: --only dev
      allow_failure: true

  - component: gitlab.jatic.net/jatic/devsecops/components/unit-test@1.0.0
    inputs:
      stage: unit-test
      full_execution_on_commit: true
      package_name: "${PACKAGE_NAME}"
      marker: all
      dependency: required
      poetry_install_options: --extras=onnx
      allow_failure: true

  - component: gitlab.jatic.net/jatic/devsecops/components/tr-compliance@1.0.0
    inputs:
      package_name: "${PACKAGE_NAME}"
      full_execution_on_commit: true
      allow_failure: true

  - component: gitlab.jatic.net/jatic/devsecops/components/dsor-compliance@1.0.0
    inputs:
      full_execution_on_commit: true
      sast_excluded_paths: "docs,output,tests,verification,.github,.gitlab,.nox,.venv"
      sast_search_max_depth: "2"
      allow_failure: true

  - component: gitlab.jatic.net/jatic/devsecops/components/advana-compliance@1.0.0
    inputs:
      full_execution_on_commit: true
      allow_failure: true

  - component: gitlab.jatic.net/jatic/devsecops/components/validate-pipeline@1.0.0
    inputs:
      full_execution_on_commit: true

  - component: gitlab.jatic.net/jatic/devsecops/components/pipeline-report@1.0.0
    inputs:
      full_execution_on_commit: true
      components_branch: 1.0.0
