### SECURITY STAGE JOBS ###

include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

.security_rules: &security_rules
  - if: $CREATE_NEW_RELEASE || $CI_COMMIT_BRANCH == 'main'
    when: never
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  - if: $CI_COMMIT_REF_PROTECTED == "true"

secret_detection:
  stage: security
  needs: []
  rules: *security_rules

gemnasium-python-dependency_scanning:
  stage: security
  needs: []
  rules: *security_rules

semgrep-sast:
  stage: security
  needs: []
  rules: *security_rules
